version: "3.8"
services:
    #=============Client Config=============
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: ./Dockerfile
        image: webapp-client
        # restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        tty: true
        env_file:
            - ./client/.env.development.local
        environment: 
            CHOKIDAR_USEPOLLING: "true"
            REACT_APP_NODE_ENV: local
        links:
            - server
        depends_on: 
            - server
        # command: "npm start"
    #=============Server Config============= 
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: ./Dockerfile
        image: webapp-server
        # restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./server:/server
            - /server/node_modules
        tty: true
        env_file:
            #copy env variables
            - ./server/.env
        environment:
            CHOKIDAR_USEPOLLING: "true"
            NODE_ENV: local
        # command: "npm start"

